accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("", views.users, name="users"),

    path('<int:user_id>/profile/', views.profile, name='profile'),

    path('<int:user_id>/follow/', views.follow, name='follow'),

    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),

]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),  # 기본 URL에 대한 뷰 연결
    path("create/", views.create, name="product_create"), #생성
    path("<int:pk>/", views.product_detail, name="product_detail"), #상세페이지
    path("<int:pk>/delete/", views.product_delete, name="product_delete"),
    path("<int:pk>/update/", views.product_update, name="product_update"),


    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path("<int:pk>/like/", views.like_product, name="like_product"),  # 찜 기능 URL

    path('liked/', views.liked_products, name='liked_products'),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #첫화면은 상품리스트
    path('', include('products.urls')),
    #사용자
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# accounts/models.py

from django.conf import settings
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='following_profiles', blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True, default='default_profile.png')

    def __str__(self):
        return self.user.username

    @property
    def follower_count(self):
        return self.followers.count()

    @property
    def following_count(self):
        return self.user.following_profiles.count()

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.urls import reverse
from django import forms
from .models import Profile

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ()


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = [
            "first_name",
            "email",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.fields.get("password"):
            password_help_text = (
                "You can change the password " '<a href="{}">here</a>.'
            ).format(f"{reverse('accounts:change_password')}")
            self.fields["password"].help_text = password_help_text

class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image']

accounts/views.py
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm, )
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_http_methods
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Profile
from .forms import ProfileImageForm


# 로그인
@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.GET.get("next") or "products:product_list"
            return redirect(next_url)
    else:
        form = AuthenticationForm()

    context = {"form": form}
    return render(request, "login.html", context)


# 로그아웃
@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("products:product_list")


# 사용자 업데이트
@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:update")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "update.html", context)


# 패스워드 변경
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:update")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "change_password.html", context)


# 회원가입
@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # 프로필 생성
            Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect("products:product_list")
    else:
        form = CustomUserCreationForm()

    context = {"form": form}
    return render(request, "signup.html", context)


def users(request):
    return render(request, "users/users.html")


@require_POST
def follow(request, user_id):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if member != request.user:
            if member.followers.filter(pk=request.user.pk).exists():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("users:profile", username=member.username)
    return redirect("accounts:login")


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect("products:product_list")


# Create your views here.
@login_required
def profile(request, user_id):
    user = get_object_or_404(get_user_model(), pk=user_id)
    profile = get_object_or_404(Profile, user=user)

    if request.method == 'POST':
        form = ProfileImageForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', user_id=user_id)
    else:
        form = ProfileImageForm(instance=profile)

    context = {
        'user': user,
        'profile': profile,
        'form': form,
    }
    return render(request, 'profile.html', context)


@require_POST
def follow(request, user_id):
    if request.user.is_authenticated:
        user = get_object_or_404(get_user_model(), pk=user_id)

        # Profile이 없으면 생성
        profile, created = Profile.objects.get_or_create(user=user)

        if user != request.user:
            if profile.followers.filter(pk=request.user.pk).exists():
                profile.followers.remove(request.user)
            else:
                profile.followers.add(request.user)

        return redirect('accounts:profile', user_id=user_id)

    return redirect('accounts:login')

accounts/templates/change_password.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>비밀번호 변경</h1>
        <form action="{% url "accounts:change_password" %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="d-grid gap-2">
                <input type="submit" value="비밀번호 변경" class="btn btn-primary">
            </div>
        </form>
    </div>
{% endblock content %}

accounts/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h2>로그인폼</h2>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="d-grid gap-2">
                <input type="submit" value="로그인" class="btn btn-primary">
            </div>
        </form>
    </div>
{% endblock content %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4 text-center">
                <h1>{{ user.first_name|default:user.username }}님 프로필</h1>

                <img style="width: 300px; height: 300px; object-fit: cover;" src="{{ profile.profile_image.url }}"
                     class="rounded-circle">

                {% if request.user == user %}

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">프로필 사진 수정</button>
                    </form>
                {% endif %}


                <div class="mt-3">
                    <p>가입일: {{ user.date_joined }}</p>
                    <p>팔로워수: <span class="badge bg-primary">{{ profile.follower_count }}</span></p>
                    <p>팔로잉수: <span class="badge bg-secondary">{{ profile.following_count }}</span></p>
                </div>
                <div class="d-flex justify-content-center mt-4">
                    {% if request.user == user %}
                        <a href="{% url 'accounts:update' %}" class="btn btn-outline-primary me-2">회원정보 수정</a>
                    {% endif %}

                    {% if request.user != user %}
                        {% if request.user in profile.followers.all %}
                            <form action="{% url 'accounts:follow' user.id %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" value="언팔로우" class="btn btn-primary">
                            </form>
                        {% else %}
                            <form action="{% url 'accounts:follow' user.id %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" value="팔로우" class="btn btn-primary">
                            </form>
                        {% endif %}
                    {% endif %}


                    {% if request.user == user %}
                        <form action="{% url 'accounts:delete' %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="회원 탈퇴" class="btn btn-danger">
                        </form>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-8">
                <h2>등록한 물건</h2>
                <ul class="list-group">
                    {% for product in user.products.all %}
                        <li class="list-group-item">
                            <a href="{% url 'products:product_detail' product.id %}">
                                {{ product.title }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <h2 class="mt-4">찜한 물건</h2>
                <ul class="list-group">

                    {% for product in user.liked_products.all %}
                        <li class="list-group-item">
                            <a href="{% url 'products:product_detail' product.id %}">
                                {{ product.title }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/signup.html
{% extends "base.html" %}
{% block content %}
    <h1>회원가입</h1>
    <form action="{% url "accounts:signup" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-2">
            <input type="submit" value="회원가입" class="btn btn-primary">
        </div>
    </form>
{% endblock content %}

accounts/templates/update.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>회원 정보 수정</h1>
        <form action="{% url "accounts:update" %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="d-grid gap-2">
                <input type="submit" value="수정" class="btn btn-primary">
            </div>
        </form>
    </div>
{% endblock %}