accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("", views.users, name="users"),

    path('<int:user_id>/profile/', views.profile, name='profile'),

    path('<int:user_id>/follow/', views.follow, name='follow'),

    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),

]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),  # 기본 URL에 대한 뷰 연결
    path("create/", views.create, name="product_create"), #생성
    path("<int:pk>/", views.product_detail, name="product_detail"), #상세페이지
    path("<int:pk>/delete/", views.product_delete, name="product_delete"),
    path("<int:pk>/update/", views.product_update, name="product_update"),


    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path("<int:pk>/like/", views.like_product, name="like_product"),  # 찜 기능 URL

    path('liked/', views.liked_products, name='liked_products'),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #첫화면은 상품리스트
    path('', include('products.urls')),
    #사용자
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>스파르타 마켓</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <style>
        /* Style for all <label> elements inside <p> tags */
        p > label {
            display: block; /* Make the label block level for proper spacing */
            margin-bottom: 0.5rem; /* Space between label and input */
            font-weight: bold; /* Bold text for label */
            color: #333; /* Dark grey color for label text */
        }

        /* Style for <input> elements inside <p> tags */
        p > input[type="text"], p > input[type="password"], p > input[type="email"], p > input[type="file"]:focus, p > textarea[name="content"] {
            width: 100%; /* Full-width input field */
            padding: 0.5rem; /* Padding inside the input field */
            border: 1px solid #ccc; /* Light grey border for input field */
            border-radius: 0.25rem; /* Slightly rounded corners */
            box-sizing: border-box; /* Include padding and border in the element’s total width and height */
        }

        p > input[type="text"]:focus, p > input[type="password"]:focus, p > input[type="email"]:focus, p > input[type="file"]:focus, p > textarea[name="content"]:focus {
            border-color: #007bff; /* Blue border on focus */
            outline: none; /* Remove default outline */
            box-shadow: 0 0 0 0.2rem rgba(38, 143, 255, 0.25); /* Shadow effect on focus */
        }


    </style>
</head>
<body>

<header class="p-3 text-bg-dark">
    <div class="container">

        <div class="d-flex flex-wrap align-items-center  justify-content-center justify-content-lg-start">

            <a href="/"
               class="d-flex align-items-center mb-md-2 me-md-auto mb-2 mb-lg-0 text-white text-decoration-none">
                <img class="me-2 " style="width: 40px"
                     src="https://teamsparta.notion.site/image/https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2F83c75a39-3aba-4ba4-a792-7aefe4b07895%2F0034db4e-3128-4346-8542-6d7343db3cac%2Fmarket.png?table=block&id=182a9955-f856-44c9-af9a-565dc8e5c22c&spaceId=83c75a39-3aba-4ba4-a792-7aefe4b07895&width=250&userId=&cache=v2">
                <span class="fs-4">스파르타 마켓</span>
            </a>


            <form method="get" action="{% url 'products:product_list' %}"
                  class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">

                <input type="hidden" name="sort" value="{{ request.GET.sort }}">

                <input type="search" name="query" value="{{ request.GET.query }}"
                       class="form-control form-control-dark text-bg-dark"
                       placeholder="Search..." aria-label="Search">

            </form>

            <div class="text-end">
                {% if request.user.is_authenticated %}
                    <div class="dropdown text-end">
                        <a href="#"
                           class="text-secondary d-block link-body-emphasis text-decoration-none dropdown-toggle"
                           data-bs-toggle="dropdown" aria-expanded="false"><span class="text-secondary ">
                            {{ user.first_name|default:user.username }} 님                        </span>
                        </a>
                        <ul class="dropdown-menu text-small" style="">

                            <li><a class="dropdown-item"
                                   href="{% url 'accounts:profile' request.user.id %}">{{ user.first_name|default:user.username }}님
                                프로필</a></li>
                            <li><a href="{% url 'products:product_create' %}" class="dropdown-item">상품추가</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a href="#"
                                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                                   class="dropdown-item">로그아웃</a>
                        </ul>
                    </div>

                    <form id="logout-form" action="{% url 'accounts:logout' %}" method="POST" style="display: none;">
                        {% csrf_token %}
                    </form>

                {% else %}
                    <a href="{% url 'accounts:login' %}" class="btn btn-outline-light me-2">로그인</a>
                    <a href="{% url "accounts:signup" %}" class="btn btn-warning">회원가입</a>
                {% endif %}

            </div>
        </div>
    </div>
</header>

<div class="album py-5 bg-body-tertiary">
    <div class="container">

        {% block content %}
        {% endblock content %}

    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>